Numpy Basic

Assignment Questions

import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans--

Yes, there is a difference in the data type of the variables list_ and array_list.

The variable list_ is a Python list, whereas array_list is a numpy array.

You can print the data types of both variables using the type() function 

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


Ans--

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [4]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

print("Data types of elements in 'list_':")
for element in list_:
    print(type(element))

print("Data types of elements in 'array_list':")
for element in array_list:
    print(type(element))


Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [5]:
import numpy as np
arr = np.random.randint(1,10 , (3,4))

In [6]:
arr

array([[7, 6, 6, 6],
       [5, 3, 5, 1],
       [8, 6, 6, 2]])

In [7]:
arr.reshape(6,2)

array([[7, 6],
       [6, 6],
       [5, 3],
       [5, 1],
       [8, 6],
       [6, 2]])

In [8]:
arr.size

12

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [9]:
import numpy as np


In [13]:

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [14]:
import numpy as np 

In [16]:
zeros_array = np.zeros((5,5))


In [17]:
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
